FROM alpine:latest

# https://community.home-assistant.io/t/ikea-tradfri-gateway-zigbee-very-basic-working-implementation/14788/19?u=balloob
RUN apk update && \
    apk add python3 python3-dev git autoconf automake libtool gcc linux-headers

RUN apk add musl-dev
RUN mkdir -p /usr/src/app /usr/src/build
WORKDIR /usr/src/build

RUN python3 -m pip install --upgrade pip setuptools wheel

RUN python3 -m pip install cython

RUN apk add make

COPY ./script/install-coap-client.sh install-coap-client.sh
RUN ./install-coap-client.sh

COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

WORKDIR /usr/src/app
ENV LANG=C.UTF-8
CMD /bin/bash



